[project]
name = "linkedin-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.5.1",
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "streamlit>=1.46.0",
    "yfinance>=0.2.63",
]
